In [74]:
import numpy as n

In [75]:
M=np.zeros((7,7))
conv=np.zeros((M.shape[0]-kernel.shape[0]+1,M.shape[0]-kernel.shape[0]+1))
cache=np.zeros((3,3))
#Create input array
for i in range(7):
    k=7*i
    for j in range(7):
        M[i][j]=2*(k+j)
print('input matrix\n',M)
#Create kernel matrix
kernel=np.array([[1,2,4],[2,4,16],[4,8,64]])
#column1->colum5
for i in range(M.shape[0]-kernel.shape[0]+1):
    for j in range(M.shape[0]-kernel.shape[0]+1):
        for ii in range(kernel.shape[0]):
            for jj in range(kernel.shape[1]):
                cache[ii][jj]=kernel[ii][jj]*M[i+ii][j+jj]
                #To check:
                #print(ii,jj,i+ii,j+jj)          
        conv[i][j]=np.sum(cache)
print('Result:\n',conv)


input matrix
 [[ 0.  2.  4.  6.  8. 10. 12.]
 [14. 16. 18. 20. 22. 24. 26.]
 [28. 30. 32. 34. 36. 38. 40.]
 [42. 44. 46. 48. 50. 52. 54.]
 [56. 58. 60. 62. 64. 66. 68.]
 [70. 72. 74. 76. 78. 80. 82.]
 [84. 86. 88. 90. 92. 94. 96.]]
Result:
 [[2800. 3010. 3220. 3430. 3640.]
 [4270. 4480. 4690. 4900. 5110.]
 [5740. 5950. 6160. 6370. 6580.]
 [7210. 7420. 7630. 7840. 8050.]
 [8680. 8890. 9100. 9310. 9520.]]


In [76]:
#another way to generate matrices 
M=np.arange(0,98,2).reshape(7,7)
print('input matrix\n',M)
kernel=np.array([[1,2,4],[2,4,16],[4,8,64]])
conv=np.zeros((M.shape[0]-kernel.shape[0]+1,M.shape[0]-kernel.shape[0]+1))
for i in range(M.shape[0]-kernel.shape[0]+1):
    for j in range(M.shape[0]-kernel.shape[0]+1):
        conv[i][j]=np.sum(M[i][j:j+3]*kernel[0])+np.sum(M[i+1][j:j+3]*kernel[1])+np.sum(M[i+2][j:j+3]*kernel[2])
print('Result:\n',conv)

input matrix
 [[ 0  2  4  6  8 10 12]
 [14 16 18 20 22 24 26]
 [28 30 32 34 36 38 40]
 [42 44 46 48 50 52 54]
 [56 58 60 62 64 66 68]
 [70 72 74 76 78 80 82]
 [84 86 88 90 92 94 96]]
Result:
 [[2800. 3010. 3220. 3430. 3640.]
 [4270. 4480. 4690. 4900. 5110.]
 [5740. 5950. 6160. 6370. 6580.]
 [7210. 7420. 7630. 7840. 8050.]
 [8680. 8890. 9100. 9310. 9520.]]


In [72]:
#exercise
A=2*np.arange(9).reshape(3,3)+np.ones((3,3))
kernel=np.array([[1,2],[4,6]])
conv=np.zeros((A.shape[0]-kernel.shape[0]+1,A.shape[0]-kernel.shape[0]+1))
for i in range(A.shape[0]-kernel.shape[0]+1):
    for j in range(A.shape[0]-kernel.shape[0]+1):
        conv[i][j]=np.sum(A[i][j:j+2]*kernel[0])+np.sum(A[i+1][j:j+2]*kernel[1])
print(conv)

[[ 89. 115.]
 [167. 193.]]
