In [1]:
import numpy as np
import tensorflow as tf

C:\Users\benzener\anaconda3\envs\tf-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\benzener\anaconda3\envs\tf-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\benzener\anaconda3\envs\tf-cpu\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\benzener\anaconda3\envs\tf-cpu\lib\site-packages\ten

In [32]:
M=np.zeros((7,7))
conv=np.zeros((M.shape[0]-kernel.shape[0]+1,M.shape[0]-kernel.shape[0]+1))
cache=np.zeros((3,3))
#Create input array
for i in range(7):
    k=7*i
    for j in range(7):
        M[i][j]=2*(k+j)
print('input matrix\n',M)
#Create kernel matrix
kernel=np.array([[1,2,4],[2,4,16],[4,8,64]])
#column1->colum5
for i in range(M.shape[0]-kernel.shape[0]+1):
    for j in range(M.shape[0]-kernel.shape[0]+1):
        for ii in range(kernel.shape[0]):
            for jj in range(kernel.shape[1]):
                cache[ii][jj]=kernel[ii][jj]*M[i+ii][j+jj]
                #To check:
                #print(ii,jj,i+ii,j+jj)          
        conv[i][j]=np.sum(cache)
print('Result:\n',conv)


input matrix
 [[ 0.  2.  4.  6.  8. 10. 12.]
 [14. 16. 18. 20. 22. 24. 26.]
 [28. 30. 32. 34. 36. 38. 40.]
 [42. 44. 46. 48. 50. 52. 54.]
 [56. 58. 60. 62. 64. 66. 68.]
 [70. 72. 74. 76. 78. 80. 82.]
 [84. 86. 88. 90. 92. 94. 96.]]
Result:
 [[2800. 3010. 3220. 3430. 3640.]
 [4270. 4480. 4690. 4900. 5110.]
 [5740. 5950. 6160. 6370. 6580.]
 [7210. 7420. 7630. 7840. 8050.]
 [8680. 8890. 9100. 9310. 9520.]]
